DROP TABLE IF EXISTS alert_actions;
DROP TABLE IF EXISTS risk_assessments;
DROP TABLE IF EXISTS sales;
DROP TABLE IF EXISTS inventory_batches;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS pharmacies;
